/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author JFAA
 */
public class jfArqueo extends javax.swing.JFrame {

    /**
     * Creates new form jfCierre
     */
    public jfArqueo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbHoraCierre = new javax.swing.JLabel();
        jdcFechaCierre = new com.toedter.calendar.JDateChooser();
        jlbUsuario = new javax.swing.JLabel();
        jlbCajaNro = new javax.swing.JLabel();
        jbtConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtExcel = new javax.swing.JButton();
        jbtCsv = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtUsuarioCierre = new javax.swing.JTextField();
        jdcFechaApertura = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jlbHoraApertura = new javax.swing.JLabel();
        jtxtNroArqueo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbCredito = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbContado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlbNeto = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlbDescuento = new javax.swing.JLabel();
        jlbTotalGeneral = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlbNotaCredito = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCierre = new javax.swing.JTable();
        jbtGuardar = new javax.swing.JButton();
        jlbMensaje = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtaObservacion = new javax.swing.JScrollPane();
        jtxtaObs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cierre Caja");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel9.setText("Arqueo Nro:");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel1.setText("Caja Nro:");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel2.setText("Usuario Apertura:");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setText("Fecha Cierre:");

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel7.setText("Hora Apertura:");

        jlbHoraCierre.setBackground(new java.awt.Color(0, 1, 59));
        jlbHoraCierre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlbHoraCierre.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoraCierre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbHoraCierre.setOpaque(true);

        jdcFechaCierre.setDateFormatString("yyyy-MM-dd");
        jdcFechaCierre.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N

        jlbUsuario.setBackground(new java.awt.Color(0, 1, 59));
        jlbUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbUsuario.setOpaque(true);

        jlbCajaNro.setBackground(new java.awt.Color(0, 1, 59));
        jlbCajaNro.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlbCajaNro.setForeground(new java.awt.Color(255, 255, 255));
        jlbCajaNro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCajaNro.setOpaque(true);

        jbtConsultar.setBackground(new java.awt.Color(0, 1, 59));
        jbtConsultar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jbtConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jbtConsultar.setText("Consultar");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exportar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 11))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        jbtExcel.setBackground(new java.awt.Color(0, 1, 59));
        jbtExcel.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jbtExcel.setForeground(new java.awt.Color(255, 255, 255));
        jbtExcel.setText("Excel");

        jbtCsv.setBackground(new java.awt.Color(0, 1, 59));
        jbtCsv.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jbtCsv.setForeground(new java.awt.Color(255, 255, 255));
        jbtCsv.setText("CSV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jbtExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbtCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtExcel)
                    .addComponent(jbtCsv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel12.setText("Usuario Cierre:");

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel13.setText("Fecha Apertura:");

        jtxtUsuarioCierre.setBackground(new java.awt.Color(0, 1, 59));
        jtxtUsuarioCierre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtxtUsuarioCierre.setForeground(new java.awt.Color(255, 255, 255));
        jtxtUsuarioCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtUsuarioCierre.setBorder(null);

        jdcFechaApertura.setDateFormatString("yyyy-MM-dd");
        jdcFechaApertura.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel14.setText("Hora Cierre:");

        jlbHoraApertura.setBackground(new java.awt.Color(0, 1, 59));
        jlbHoraApertura.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlbHoraApertura.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoraApertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbHoraApertura.setOpaque(true);

        jtxtNroArqueo.setBackground(new java.awt.Color(0, 1, 59));
        jtxtNroArqueo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtxtNroArqueo.setForeground(new java.awt.Color(255, 255, 255));
        jtxtNroArqueo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNroArqueo.setBorder(null);
        jtxtNroArqueo.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel1))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdcFechaApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlbHoraCierre, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(jlbHoraApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jtxtUsuarioCierre)
                                    .addComponent(jlbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCajaNro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtNroArqueo)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jbtConsultar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtNroArqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlbCajaNro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtUsuarioCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdcFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jlbHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jlbHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtConsultar)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, 430));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Orbitron", 1, 14)); // NOI18N
        jLabel5.setText("Totales:");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setText("Credito");

        jlbCredito.setBackground(new java.awt.Color(0, 1, 59));
        jlbCredito.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbCredito.setForeground(new java.awt.Color(255, 255, 255));
        jlbCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCredito.setText("0");
        jlbCredito.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setText("Contado");

        jlbContado.setBackground(new java.awt.Color(0, 1, 59));
        jlbContado.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbContado.setForeground(new java.awt.Color(255, 255, 255));
        jlbContado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbContado.setText("0");
        jlbContado.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel11.setText("Total Neto");

        jlbNeto.setBackground(new java.awt.Color(0, 1, 59));
        jlbNeto.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbNeto.setForeground(new java.awt.Color(255, 255, 255));
        jlbNeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNeto.setText("0");
        jlbNeto.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel15.setText("Descuento del día");

        jlbDescuento.setBackground(new java.awt.Color(0, 1, 59));
        jlbDescuento.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbDescuento.setForeground(new java.awt.Color(255, 255, 255));
        jlbDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbDescuento.setText("0");
        jlbDescuento.setOpaque(true);

        jlbTotalGeneral.setBackground(new java.awt.Color(0, 1, 59));
        jlbTotalGeneral.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbTotalGeneral.setForeground(new java.awt.Color(255, 255, 255));
        jlbTotalGeneral.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbTotalGeneral.setText("0");
        jlbTotalGeneral.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel16.setText("Total General");

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel17.setText("Nota de Credito");

        jlbNotaCredito.setBackground(new java.awt.Color(0, 1, 59));
        jlbNotaCredito.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbNotaCredito.setForeground(new java.awt.Color(255, 255, 255));
        jlbNotaCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNotaCredito.setText("0");
        jlbNotaCredito.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbNotaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbContado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(59, 59, 59)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jlbDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNeto)
                    .addComponent(jlbCredito)
                    .addComponent(jLabel5)
                    .addComponent(jlbContado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbDescuento)
                    .addComponent(jlbTotalGeneral)
                    .addComponent(jlbNotaCredito))
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 940, -1));

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 1, 59));
        jLabel3.setText("Detalle Venta del día");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jtCierre.setBackground(new java.awt.Color(153, 204, 255));
        jtCierre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtCierre.setForeground(new java.awt.Color(0, 1, 59));
        jtCierre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venta Nro", "Detalle Nro", "Tipo", "Producto", "Precio", "Cantidad", "Descuento", "Total Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCierre.setFocusable(false);
        jScrollPane1.setViewportView(jtCierre);
        if (jtCierre.getColumnModel().getColumnCount() > 0) {
            jtCierre.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 660, -1));

        jbtGuardar.setBackground(new java.awt.Color(153, 204, 255));
        jbtGuardar.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jbtGuardar.setForeground(new java.awt.Color(0, 102, 51));
        jbtGuardar.setText("Guardar");
        jPanel4.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, -1, 32));

        jlbMensaje.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbMensaje.setForeground(new java.awt.Color(0, 155, 0));
        jlbMensaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jlbMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 940, 24));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        jLabel8.setText("Observación:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jtxtaObs.setColumns(20);
        jtxtaObs.setRows(5);
        jtxtaObs.setText("Cierre arqueo");
        jtxtaObs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtaObservacion.setViewportView(jtxtaObs);

        jPanel4.add(txtaObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 760, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCierre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtConsultar;
    public javax.swing.JButton jbtCsv;
    public javax.swing.JButton jbtExcel;
    public javax.swing.JButton jbtGuardar;
    public com.toedter.calendar.JDateChooser jdcFechaApertura;
    public com.toedter.calendar.JDateChooser jdcFechaCierre;
    public javax.swing.JLabel jlbCajaNro;
    public javax.swing.JLabel jlbContado;
    public javax.swing.JLabel jlbCredito;
    public javax.swing.JLabel jlbDescuento;
    public javax.swing.JLabel jlbHoraApertura;
    public javax.swing.JLabel jlbHoraCierre;
    public javax.swing.JLabel jlbMensaje;
    public javax.swing.JLabel jlbNeto;
    public javax.swing.JLabel jlbNotaCredito;
    public javax.swing.JLabel jlbTotalGeneral;
    public javax.swing.JLabel jlbUsuario;
    public javax.swing.JTable jtCierre;
    public javax.swing.JTextField jtxtNroArqueo;
    public javax.swing.JTextField jtxtUsuarioCierre;
    public javax.swing.JTextArea jtxtaObs;
    public javax.swing.JScrollPane txtaObservacion;
    // End of variables declaration//GEN-END:variables
}
