/*
 * Calse que modela el formulario de filtro de productos 
 */
package Vista;

/**
 *
 * @author JFAA
 */
public class jfFiltraProducto extends javax.swing.JFrame {

    /**
     * Creates new form jfFiltraProducto
     */
    public jfFiltraProducto() {
        initComponents();
        //Colocar en el centro el formulario
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgFiltro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListado = new javax.swing.JTable();
        jpSelectorfiltro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbMarca = new javax.swing.JComboBox<>();
        jrbPorCategoria = new javax.swing.JRadioButton();
        jrbPorMarca = new javax.swing.JRadioButton();
        jpFiltro = new javax.swing.JPanel();
        jbtFiltrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro de Productos");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtListado.setBackground(new java.awt.Color(153, 204, 255));
        jtListado.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jtListado.setForeground(new java.awt.Color(0, 1, 59));
        jtListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Categoria", "Marca", "Existencia", "Costo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 680, 500));

        jpSelectorfiltro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selector de Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N
        jpSelectorfiltro.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel1.setText("Categoria");

        jcbCategoria.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jcbCategoria.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel2.setText("Marca");

        jcbMarca.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jcbMarca.setEnabled(false);

        btgFiltro.add(jrbPorCategoria);
        jrbPorCategoria.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbPorCategoria.setText("Por Categoria ");
        jrbPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorCategoriaActionPerformed(evt);
            }
        });

        btgFiltro.add(jrbPorMarca);
        jrbPorMarca.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbPorMarca.setText("Por Marca");
        jrbPorMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSelectorfiltroLayout = new javax.swing.GroupLayout(jpSelectorfiltro);
        jpSelectorfiltro.setLayout(jpSelectorfiltroLayout);
        jpSelectorfiltroLayout.setHorizontalGroup(
            jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelectorfiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMarca, 0, 162, Short.MAX_VALUE)
                    .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbPorCategoria)
                    .addComponent(jrbPorMarca))
                .addGap(21, 21, 21))
        );
        jpSelectorfiltroLayout.setVerticalGroup(
            jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelectorfiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSelectorfiltroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpSelectorfiltroLayout.createSequentialGroup()
                        .addGroup(jpSelectorfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbPorCategoria)
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jrbPorMarca)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jpSelectorfiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, 120));

        jpFiltro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtFiltrar.setBackground(new java.awt.Color(153, 204, 255));
        jbtFiltrar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jbtFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtFiltrar.setText("Filtrar");
        jbtFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpFiltroLayout = new javax.swing.GroupLayout(jpFiltro);
        jpFiltro.setLayout(jpFiltroLayout);
        jpFiltroLayout.setHorizontalGroup(
            jpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpFiltroLayout.setVerticalGroup(
            jpFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jbtFiltrar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(jpFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 100, 110));

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 1, 59));
        jLabel3.setText("Listado de Productos según filtro seleccionado");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Exportar"));

        jbtExcel.setBackground(new java.awt.Color(153, 204, 255));
        jbtExcel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtExcel.setForeground(new java.awt.Color(0, 102, 51));
        jbtExcel.setText("Excel");
        jbtExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtExcel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbtExcel)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 100, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPorCategoriaActionPerformed

    private void jrbPorMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPorMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfFiltraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfFiltraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfFiltraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfFiltraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfFiltraProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btgFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtExcel;
    public javax.swing.JButton jbtFiltrar;
    public javax.swing.JComboBox<String> jcbCategoria;
    public javax.swing.JComboBox<String> jcbMarca;
    public javax.swing.JPanel jpFiltro;
    public javax.swing.JPanel jpSelectorfiltro;
    public javax.swing.JRadioButton jrbPorCategoria;
    public javax.swing.JRadioButton jrbPorMarca;
    public javax.swing.JTable jtListado;
    // End of variables declaration//GEN-END:variables
}
