package Vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import static javafx.scene.paint.Color.color;

/**
 *
 * @author JFAA
 */
public class jfIngreso extends javax.swing.JFrame {
/*SE CREA DSO VARIABLES PARA LA POSICION DE LAS EJES PARA POSICIONAR LOS EVENTOS
    */
    int xMouse;
    int yMouse;
    /**
     * Creates new form jfIngreso
     */
    public jfIngreso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public static String Usuario="";
     public static String NroCaja="";
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jfpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        btnAcceder = new javax.swing.JButton();
        jlbHora = new javax.swing.JLabel();
        jblUsuario = new javax.swing.JLabel();
        jcbNroCaja = new javax.swing.JComboBox<>();
        jblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        haeder = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        jblValidarU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso al Sistema Dolly");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(680, 345));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jfpass.setBackground(new java.awt.Color(153, 204, 255));
        jfpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfpass.setText("********");
        jfpass.setBorder(null);
        jfpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jfpassMousePressed(evt);
            }
        });
        jfpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jfpassKeyPressed(evt);
            }
        });
        jPanel1.add(jfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 161, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 1, 56));
        jLabel2.setText("Nro. de Caja");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 30));

        jdcFecha.setBackground(new java.awt.Color(153, 204, 255));
        jdcFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 1, 56)));
        jdcFecha.setForeground(new java.awt.Color(0, 1, 56));
        jdcFecha.setToolTipText("");
        jdcFecha.setDateFormatString("yyyy-MM-dd");
        jdcFecha.setEnabled(false);
        jdcFecha.setFocusable(false);
        jPanel1.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 108, -1));

        btnAcceder.setBackground(new java.awt.Color(153, 204, 255));
        btnAcceder.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(0, 1, 56));
        btnAcceder.setText("Acceder");
        btnAcceder.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 1, 59)));
        btnAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccederMouseExited(evt);
            }
        });
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 40));

        jlbHora.setBackground(new java.awt.Color(153, 204, 255));
        jlbHora.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jlbHora.setForeground(new java.awt.Color(0, 1, 56));
        jlbHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHora.setFocusable(false);
        jlbHora.setOpaque(true);
        jPanel1.add(jlbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 330, 108, 22));

        jblUsuario.setBackground(new java.awt.Color(204, 204, 255));
        jblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblUsuario.setForeground(new java.awt.Color(0, 1, 56));
        jblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jblUsuario.setText("Usuario");
        jPanel1.add(jblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 30));

        jcbNroCaja.setBackground(new java.awt.Color(153, 204, 255));
        jcbNroCaja.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jcbNroCaja.setForeground(new java.awt.Color(0, 1, 59));
        jcbNroCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jcbNroCaja.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 1, 59)));
        jcbNroCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jcbNroCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 40, 30));

        jblContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblContraseña.setForeground(new java.awt.Color(0, 1, 56));
        jblContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jblContraseña.setText("Contraseña");
        jPanel1.add(jblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 122, -1, 30));

        txtUsuario.setBackground(new java.awt.Color(153, 204, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("Ingrese Su Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 161, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cg-login-.jpg"))); // NOI18N
        jLabel4.setText("img_logo");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 350, 360));

        jSeparator1.setBackground(new java.awt.Color(12, 6, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, -1));

        jSeparator3.setBackground(new java.awt.Color(12, 6, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 160, -1));

        haeder.setBackground(new java.awt.Color(153, 204, 255));
        haeder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                haederMouseDragged(evt);
            }
        });
        haeder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                haederMousePressed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(153, 204, 255));
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbtnMouseExited(evt);
            }
        });

        x.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        x.setForeground(new java.awt.Color(0, 1, 56));
        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jblValidarU.setBackground(new java.awt.Color(204, 204, 255));
        jblValidarU.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        jblValidarU.setForeground(new java.awt.Color(0, 1, 56));
        jblValidarU.setText("LOGIN");
        jblValidarU.setFocusable(false);

        javax.swing.GroupLayout haederLayout = new javax.swing.GroupLayout(haeder);
        haeder.setLayout(haederLayout);
        haederLayout.setHorizontalGroup(
            haederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haederLayout.createSequentialGroup()
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(jblValidarU)
                .addGap(0, 188, Short.MAX_VALUE))
        );
        haederLayout.setVerticalGroup(
            haederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(haederLayout.createSequentialGroup()
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, haederLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblValidarU))
        );

        jPanel1.add(haeder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        Usuario=txtUsuario.getText();
        if (txtUsuario.getText().equals("JCardozo") && txtUsuario.getText().equals( "rcar")){
            NroCaja=jcbNroCaja.getSelectedItem().toString();            
        }else{
            NroCaja="1";            
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void haederMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haederMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_haederMousePressed

    private void haederMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haederMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_haederMouseDragged

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        //PARA PODER SALIR AL DARLE CLICK AL PANER. ES EL EVENTO CLICK
        System.exit(0);
    }//GEN-LAST:event_exitbtnMouseClicked

    private void exitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseEntered
     
    }//GEN-LAST:event_exitbtnMouseEntered

    private void exitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseExited
        
    }//GEN-LAST:event_exitbtnMouseExited

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // Condición para poder vaciar el campo Usuario"txtUsuario" al hacer click con el mouse :
       if(txtUsuario.getText().equals("Ingrese Su Usuario")){
       txtUsuario.setText("");
       txtUsuario.setForeground(Color.black);
       }
       if(String.valueOf(jfpass.getPassword()).isEmpty()){
       jfpass.setText("********");
       jfpass.setForeground(Color.gray);
       }
       
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void jfpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfpassMousePressed
        // Condición para poder vaciar el campo Password"jfpass" al hacer click con el mouse:
        
        if(String.valueOf(jfpass.getPassword()).equals("********")){
       jfpass.setText("");
       jfpass.setForeground(Color.black);
       }
     if(txtUsuario.getText().isEmpty()){
         txtUsuario.setText("Ingrese Su Usuario");
         txtUsuario.setForeground(Color.gray);
     }
    }//GEN-LAST:event_jfpassMousePressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        //condición para que baje del usuario a la cintraseña al pulsar enter
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jfpass.requestFocus();
        }
        // Condición para poder vaciar el campo Usuario"txtUsuario" al tocar cualquier tecla:
          if(txtUsuario.getText().equals("Ingrese Su Usuario")){
       txtUsuario.setText("");
       txtUsuario.setForeground(Color.black);
       }
       if(String.valueOf(jfpass.getPassword()).isEmpty()){
       jfpass.setText("********");
       jfpass.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void jfpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfpassKeyPressed
       //
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
         
        }
        // Condición para poder vaciar el campo Password"jfpass" al tocar cualquier tecla:
        if(String.valueOf(jfpass.getPassword()).equals("********")){
       jfpass.setText("");
       jfpass.setForeground(Color.black);
       }
     if(txtUsuario.getText().isEmpty()){
         txtUsuario.setText("Ingrese Su Usuario");
         txtUsuario.setForeground(Color.gray);
     }
    }//GEN-LAST:event_jfpassKeyPressed

    private void xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_xMousePressed

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        //SIRVE PARA EL EVENTO DE CUANDO SE PASA EL CURSOR ENCIMA DEL BOTON SE VUELVA A PONER BLANCO
   exitbtn.setBackground(new Color(153,204,255));
        x.setForeground(new Color(0,1,56));
    }//GEN-LAST:event_xMouseExited

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        // ES EL EVENTO EN DONDE PASAMOS EL MOUSE POR EL PANEL Y CAMBIAR DE COLOR A ROJO
        exitbtn.setBackground(Color.RED);
        x.setBackground(Color.red);
        x.setForeground(Color.white);
   
    }//GEN-LAST:event_xMouseEntered

    private void btnAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseEntered
        // La acción para la animacion de cuando pasa el cursor encima del boton al ENTRAR
        btnAcceder.setForeground(Color.white);
        btnAcceder.setBackground(new Color(1,0,67));
    }//GEN-LAST:event_btnAccederMouseEntered

    private void btnAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseExited
        // La animacion para la animacion de cuando pasa el cursor encima del boton al SALIR
        btnAcceder.setForeground(new Color(0,1,59));
        btnAcceder.setBackground(new Color(155,200,255));
    }//GEN-LAST:event_btnAccederMouseExited

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAcceder;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JPanel haeder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel jblContraseña;
    public javax.swing.JLabel jblUsuario;
    public javax.swing.JLabel jblValidarU;
    public javax.swing.JComboBox<String> jcbNroCaja;
    public com.toedter.calendar.JDateChooser jdcFecha;
    public javax.swing.JPasswordField jfpass;
    public javax.swing.JLabel jlbHora;
    public javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables

    private Object getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void bntAcceder() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void ControlAcceso() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
