package Vista;

import Controlador.Fondo;
import java.awt.Color;

/**
 *
 * @author JFAA
 */
public class jfVenta extends javax.swing.JFrame {
    public static String codPro="";
    public int costo=0, ganancia=0;
    String url="/img/img1.jpg";
    Fondo fndo;
    //FondoPanel fondo=new FondoPanel(url);
    /**
     * Creates new form jfVenta
     */
    public jfVenta() {        
        this.fndo = new Fondo(url);
        this.setContentPane(fndo);
        //setBackground(new Color(102,255,255));
        initComponents();
        this.setLocationRelativeTo(null);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgModoPago = new javax.swing.ButtonGroup();
        btgTipoCliente = new javax.swing.ButtonGroup();
        jpFondo = new Fondo();
        jPTipoVenta = new javax.swing.JPanel();
        jrbContado = new javax.swing.JRadioButton();
        jrbCredito = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalle = new javax.swing.JTable();
        jpTipocliente = new javax.swing.JPanel();
        jrbMostrador = new javax.swing.JRadioButton();
        jrbPuestoobra = new javax.swing.JRadioButton();
        jrbFerreteria = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jpCalculadora = new javax.swing.JPanel();
        txtMonto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlbVuelto = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtTotalG = new javax.swing.JTextField();
        jtxtTotalDescuento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtxtDescuento = new javax.swing.JTextField();
        txtTotalCobrar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtxtLimiteDescuento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jcbLote = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jbtBuscarP = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtxtLimite = new javax.swing.JTextField();
        jtxtStock = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNrofactura = new javax.swing.JTextField();
        jlNroCaja = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        JDCfechafactura = new com.toedter.calendar.JDateChooser();
        jlbCajero = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtEstado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtArqueo = new javax.swing.JTextField();
        Timbrado = new javax.swing.JLabel();
        jtxtTimbrado = new javax.swing.JTextField();
        jlbFechaInicio = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlbFechaFin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtBuscarCli = new javax.swing.JButton();
        txtRuc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNroci = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtNroPresupuesto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venta");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTipoVenta.setBackground(new java.awt.Color(153, 204, 255));
        jPTipoVenta.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 1, 59)));
        jPTipoVenta.setFocusable(false);

        jrbContado.setBackground(new java.awt.Color(153, 204, 255));
        btgModoPago.add(jrbContado);
        jrbContado.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbContado.setForeground(new java.awt.Color(0, 1, 59));
        jrbContado.setText("Contado");

        jrbCredito.setBackground(new java.awt.Color(153, 204, 255));
        btgModoPago.add(jrbCredito);
        jrbCredito.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbCredito.setForeground(new java.awt.Color(0, 1, 59));
        jrbCredito.setText("Credito");

        jLabel27.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 1, 59));
        jLabel27.setText("Tipo Venta:");

        javax.swing.GroupLayout jPTipoVentaLayout = new javax.swing.GroupLayout(jPTipoVenta);
        jPTipoVenta.setLayout(jPTipoVentaLayout);
        jPTipoVentaLayout.setHorizontalGroup(
            jPTipoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTipoVentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbContado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCredito)
                .addGap(8, 8, 8))
            .addGroup(jPTipoVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTipoVentaLayout.setVerticalGroup(
            jPTipoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTipoVentaLayout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPTipoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbContado)
                    .addComponent(jrbCredito)))
        );

        jpFondo.add(jPTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, 60));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 1, 59));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventas");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 1, 59)));
        jLabel1.setOpaque(true);
        jpFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 210, -1));

        jScrollPane1.setOpaque(false);

        jtDetalle.setBackground(new java.awt.Color(153, 204, 255));
        jtDetalle.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtDetalle.setForeground(new java.awt.Color(0, 1, 59));
        jtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producto", "Lote", "Descripción", "Limite", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDetalle.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtDetalle.setFocusable(false);
        jtDetalle.setGridColor(new java.awt.Color(153, 204, 255));
        jtDetalle.setSelectionBackground(new java.awt.Color(0, 1, 59));
        jScrollPane1.setViewportView(jtDetalle);
        if (jtDetalle.getColumnModel().getColumnCount() > 0) {
            jtDetalle.getColumnModel().getColumn(0).setResizable(false);
            jtDetalle.getColumnModel().getColumn(0).setPreferredWidth(110);
            jtDetalle.getColumnModel().getColumn(1).setResizable(false);
            jtDetalle.getColumnModel().getColumn(1).setPreferredWidth(110);
            jtDetalle.getColumnModel().getColumn(2).setPreferredWidth(230);
            jtDetalle.getColumnModel().getColumn(3).setResizable(false);
            jtDetalle.getColumnModel().getColumn(4).setResizable(false);
            jtDetalle.getColumnModel().getColumn(4).setPreferredWidth(86);
            jtDetalle.getColumnModel().getColumn(5).setResizable(false);
            jtDetalle.getColumnModel().getColumn(6).setResizable(false);
            jtDetalle.getColumnModel().getColumn(6).setPreferredWidth(130);
        }

        jpFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 920, 210));

        jpTipocliente.setBackground(new java.awt.Color(153, 204, 255));
        jpTipocliente.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 1, 59)));
        jpTipocliente.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N

        jrbMostrador.setBackground(new java.awt.Color(153, 204, 255));
        btgTipoCliente.add(jrbMostrador);
        jrbMostrador.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbMostrador.setForeground(new java.awt.Color(0, 1, 59));
        jrbMostrador.setText("Mostrador");

        jrbPuestoobra.setBackground(new java.awt.Color(153, 204, 255));
        btgTipoCliente.add(jrbPuestoobra);
        jrbPuestoobra.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbPuestoobra.setForeground(new java.awt.Color(0, 1, 59));
        jrbPuestoobra.setText("Entrega a Domicilio");
        jrbPuestoobra.setEnabled(false);

        jrbFerreteria.setBackground(new java.awt.Color(153, 204, 255));
        btgTipoCliente.add(jrbFerreteria);
        jrbFerreteria.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jrbFerreteria.setForeground(new java.awt.Color(0, 1, 59));
        jrbFerreteria.setText("Revendedor");
        jrbFerreteria.setEnabled(false);
        jrbFerreteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFerreteriaActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 1, 59));
        jLabel28.setText("Tipo Cliente:");

        javax.swing.GroupLayout jpTipoclienteLayout = new javax.swing.GroupLayout(jpTipocliente);
        jpTipocliente.setLayout(jpTipoclienteLayout);
        jpTipoclienteLayout.setHorizontalGroup(
            jpTipoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTipoclienteLayout.createSequentialGroup()
                .addComponent(jrbMostrador)
                .addGap(38, 38, 38)
                .addComponent(jrbPuestoobra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jrbFerreteria)
                .addGap(15, 15, 15))
            .addGroup(jpTipoclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTipoclienteLayout.setVerticalGroup(
            jpTipoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTipoclienteLayout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jpTipoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMostrador)
                    .addComponent(jrbPuestoobra)
                    .addComponent(jrbFerreteria)))
        );

        jpFondo.add(jpTipocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 60));

        jpCalculadora.setBackground(new java.awt.Color(153, 204, 255));
        jpCalculadora.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 1, 59)));
        jpCalculadora.setForeground(new java.awt.Color(51, 51, 51));

        txtMonto.setBackground(new java.awt.Color(0, 3, 178));
        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(255, 255, 255));
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMonto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 1, 59));
        jLabel16.setText("Monto entregado");

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 1, 59));
        jLabel17.setText("Vuelto");

        jlbVuelto.setBackground(new java.awt.Color(0, 1, 59));
        jlbVuelto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbVuelto.setForeground(new java.awt.Color(255, 255, 255));
        jlbVuelto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbVuelto.setText("0 Gs");
        jlbVuelto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbVuelto.setOpaque(true);

        jLabel29.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 1, 59));
        jLabel29.setText("Calculadora de Vuelto");

        javax.swing.GroupLayout jpCalculadoraLayout = new javax.swing.GroupLayout(jpCalculadora);
        jpCalculadora.setLayout(jpCalculadoraLayout);
        jpCalculadoraLayout.setHorizontalGroup(
            jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCalculadoraLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculadoraLayout.createSequentialGroup()
                        .addComponent(jlbVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculadoraLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculadoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(71, 71, 71))
        );
        jpCalculadoraLayout.setVerticalGroup(
            jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCalculadoraLayout.createSequentialGroup()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFondo.add(jpCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 330, 90));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(0, 1, 59)));

        txtTotalG.setEditable(false);
        txtTotalG.setBackground(new java.awt.Color(0, 1, 59));
        txtTotalG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalG.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalG.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalG.setText("0");
        txtTotalG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtTotalDescuento.setEditable(false);
        jtxtTotalDescuento.setBackground(new java.awt.Color(0, 1, 59));
        jtxtTotalDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTotalDescuento.setForeground(new java.awt.Color(255, 255, 255));
        jtxtTotalDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTotalDescuento.setText("0");
        jtxtTotalDescuento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 1, 59));
        jLabel20.setText("Total");

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 1, 59));
        jLabel22.setText("Descuento");

        jtxtDescuento.setBackground(new java.awt.Color(0, 3, 178));
        jtxtDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtDescuento.setForeground(new java.awt.Color(255, 255, 255));
        jtxtDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDescuento.setText("0");
        jtxtDescuento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTotalCobrar.setEditable(false);
        txtTotalCobrar.setBackground(new java.awt.Color(0, 1, 59));
        txtTotalCobrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalCobrar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalCobrar.setText("0");
        txtTotalCobrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 1, 59));
        jLabel23.setText("A cobrar");

        jtxtLimiteDescuento.setEditable(false);
        jtxtLimiteDescuento.setBackground(new java.awt.Color(0, 1, 59));
        jtxtLimiteDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtLimiteDescuento.setForeground(new java.awt.Color(255, 255, 255));
        jtxtLimiteDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtLimiteDescuento.setText("0");
        jtxtLimiteDescuento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 1, 59));
        jLabel24.setText("Límite Dcto.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalCobrar)
                            .addComponent(txtTotalG)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtTotalDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jtxtLimiteDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotalDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtLimiteDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtTotalCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jpFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 330, 150));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 1, 59)));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 1, 59));
        jLabel7.setText("Producto");

        txtCodigo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jcbLote.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jcbLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLoteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 1, 59));
        jLabel8.setText("Lote");

        txtDescripcion.setEditable(false);
        txtDescripcion.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 153, 153));

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(204, 0, 0));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 1, 59));
        jLabel13.setText("Precio");

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 1, 59));
        jLabel9.setText("Cantidad");

        txtCantidad.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 1, 59));
        jLabel10.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 0, 51));
        txtTotal.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 0, 51));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTotal.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 1, 59));
        jLabel11.setText("Descripción");

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 1, 59));
        jLabel25.setText("Límite");

        jtxtLimite.setEditable(false);
        jtxtLimite.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtxtLimite.setForeground(new java.awt.Color(51, 121, 90));

        jtxtStock.setEditable(false);
        jtxtStock.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 1, 59));
        jLabel26.setText("Stock Actual");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jbtBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jcbLote, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(123, 123, 123)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(81, 81, 81))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtBuscarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(jLabel13)
                                .addComponent(jLabel9)
                                .addComponent(jLabel26)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1060, 80));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 1, 59)));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 1, 59));
        jLabel5.setText("Nro. Venta");

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 1, 59));
        jLabel12.setText("Nro. Term./Usu");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 1, 59));
        jLabel6.setText("Fecha");

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 1, 59));
        jLabel15.setText("Cajero/a");

        txtNrofactura.setEditable(false);
        txtNrofactura.setBackground(new java.awt.Color(0, 1, 59));
        txtNrofactura.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtNrofactura.setForeground(new java.awt.Color(255, 255, 255));

        jlNroCaja.setBackground(new java.awt.Color(0, 1, 59));
        jlNroCaja.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlNroCaja.setForeground(new java.awt.Color(255, 255, 255));
        jlNroCaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlNroCaja.setFocusable(false);
        jlNroCaja.setOpaque(true);

        jlUsuario.setBackground(new java.awt.Color(0, 1, 59));
        jlUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlUsuario.setFocusable(false);
        jlUsuario.setOpaque(true);

        JDCfechafactura.setBackground(new java.awt.Color(0, 1, 59));
        JDCfechafactura.setForeground(new java.awt.Color(255, 255, 255));
        JDCfechafactura.setDateFormatString("yyyy-MM-dd");
        JDCfechafactura.setEnabled(false);
        JDCfechafactura.setFocusable(false);
        JDCfechafactura.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        jlbCajero.setBackground(new java.awt.Color(0, 1, 59));
        jlbCajero.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jlbCajero.setForeground(new java.awt.Color(255, 255, 255));
        jlbCajero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCajero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbCajero.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 1, 59));
        jLabel18.setText("Estado");

        jtxtEstado.setBackground(new java.awt.Color(0, 1, 59));
        jtxtEstado.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtxtEstado.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEstado.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 1, 59));
        jLabel19.setText("Arqueo Nro.");

        jtxtArqueo.setBackground(new java.awt.Color(0, 1, 59));
        jtxtArqueo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtxtArqueo.setForeground(new java.awt.Color(255, 255, 255));
        jtxtArqueo.setBorder(null);

        Timbrado.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Timbrado.setForeground(new java.awt.Color(0, 1, 59));
        Timbrado.setText("Timbrado Nro.");

        jtxtTimbrado.setBackground(new java.awt.Color(0, 1, 59));
        jtxtTimbrado.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jtxtTimbrado.setForeground(new java.awt.Color(255, 255, 255));
        jtxtTimbrado.setBorder(null);

        jlbFechaInicio.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbFechaInicio.setForeground(new java.awt.Color(0, 1, 59));
        jlbFechaInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 1, 59)));

        jLabel21.setText("/");

        jlbFechaFin.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlbFechaFin.setForeground(new java.awt.Color(0, 1, 59));
        jlbFechaFin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 1, 59)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(Timbrado)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlbFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNrofactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlNroCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jtxtArqueo)
                            .addComponent(jtxtTimbrado))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jlbFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JDCfechafactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNrofactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNroCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(JDCfechafactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addComponent(jtxtArqueo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Timbrado)
                    .addComponent(jtxtTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jlbFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jpFondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, 280));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 1, 59)));

        jbtBuscarCli.setBackground(new java.awt.Color(0, 1, 59));
        jbtBuscarCli.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jbtBuscarCli.setForeground(new java.awt.Color(255, 255, 255));
        jbtBuscarCli.setText("Buscar");
        jbtBuscarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtRuc.setEditable(false);
        txtRuc.setBackground(new java.awt.Color(0, 1, 59));
        txtRuc.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtRuc.setForeground(new java.awt.Color(255, 255, 255));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(0, 1, 59));
        txtNombre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setCaretColor(new java.awt.Color(0, 1, 59));

        txtNroci.setBackground(new java.awt.Color(0, 1, 59));
        txtNroci.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtNroci.setForeground(new java.awt.Color(255, 255, 255));
        txtNroci.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNroci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrociActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 1, 59));
        jLabel4.setText("Nro. Cédula:");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 1, 59));
        jLabel2.setText("R.U.C Cliente:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 1, 59));
        jLabel3.setText("Nombre y Apellido:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNroci, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtBuscarCli))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtNroci, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtBuscarCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRuc, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 120));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 1, 59)));
        jPanel5.setForeground(new java.awt.Color(0, 1, 59));
        jPanel5.setFont(new java.awt.Font("Lucida Sans", 1, 17)); // NOI18N

        txtNroPresupuesto.setBackground(new java.awt.Color(0, 1, 59));
        txtNroPresupuesto.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtNroPresupuesto.setForeground(new java.awt.Color(255, 255, 255));
        txtNroPresupuesto.setBorder(null);
        txtNroPresupuesto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNroPresupuesto.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 1, 59));
        jLabel14.setText("Nro. Ticket:");

        btnBuscar.setBackground(new java.awt.Color(0, 1, 59));
        btnBuscar.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNroPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(17, 17, 17)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNroPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(btnBuscar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jpFondo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 90));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregar.setBackground(new java.awt.Color(153, 204, 255));
        btnAgregar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 1, 59));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtEliminar.setBackground(new java.awt.Color(153, 204, 255));
        jbtEliminar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtEliminar.setForeground(new java.awt.Color(255, 0, 0));
        jbtEliminar.setText("Eliminar");
        jbtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRegistrar.setBackground(new java.awt.Color(153, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 102, 51));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(28, 28, 28)
                .addComponent(btnRegistrar)
                .addGap(26, 26, 26)
                .addComponent(jbtEliminar)
                .addGap(25, 25, 25))
        );

        jpFondo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 140, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbFerreteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFerreteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFerreteriaActionPerformed

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        //
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtNrociActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrociActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrociActionPerformed

    private void jcbLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser JDCfechafactura;
    private javax.swing.JLabel Timbrado;
    private javax.swing.ButtonGroup btgModoPago;
    private javax.swing.ButtonGroup btgTipoCliente;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPTipoVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtBuscarCli;
    public javax.swing.JButton jbtBuscarP;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JComboBox<String> jcbLote;
    public javax.swing.JLabel jlNroCaja;
    public javax.swing.JLabel jlUsuario;
    public javax.swing.JLabel jlbCajero;
    public javax.swing.JLabel jlbFechaFin;
    public javax.swing.JLabel jlbFechaInicio;
    public javax.swing.JLabel jlbVuelto;
    public javax.swing.JPanel jpCalculadora;
    public javax.swing.JPanel jpFondo;
    public javax.swing.JPanel jpTipocliente;
    public javax.swing.JRadioButton jrbContado;
    public javax.swing.JRadioButton jrbCredito;
    public javax.swing.JRadioButton jrbFerreteria;
    public javax.swing.JRadioButton jrbMostrador;
    public javax.swing.JRadioButton jrbPuestoobra;
    public javax.swing.JTable jtDetalle;
    public javax.swing.JTextField jtxtArqueo;
    public javax.swing.JTextField jtxtDescuento;
    public javax.swing.JTextField jtxtEstado;
    public javax.swing.JTextField jtxtLimite;
    public javax.swing.JTextField jtxtLimiteDescuento;
    public javax.swing.JTextField jtxtStock;
    public javax.swing.JTextField jtxtTimbrado;
    public javax.swing.JTextField jtxtTotalDescuento;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtMonto;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNroPresupuesto;
    public javax.swing.JTextField txtNroci;
    public javax.swing.JTextField txtNrofactura;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtRuc;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTotalCobrar;
    public javax.swing.JTextField txtTotalG;
    // End of variables declaration//GEN-END:variables

}